# Generated by Django 5.1.7 on 2025-04-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_client_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('rider', 'r'), ('client', 'c')], max_length=20, null=True),
        ),
    ]
