# Generated by Django 5.1.7 on 2025-04-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='rider',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='rider',
            name='service_type',
            field=models.CharField(blank=True, choices=[('both', 'b'), ('rides', 'r'), ('packages', 'p')], max_length=20, null=True),
        ),
    ]
