# Generated by Django 5.1.7 on 2025-04-30 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
