# Generated by Django 5.1.7 on 2025-04-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0003_riderlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderlocation',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='riderlocation',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
