# Generated by Django 5.1.7 on 2025-05-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0004_alter_riderlocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='booking',
            name='origin',
            field=models.JSONField(default=dict),
        ),
    ]
