# Generated by Django 5.1.7 on 2025-05-01 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0005_booking_destination_booking_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ride_bookings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
