# Generated by Django 5.1.7 on 2025-05-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideapp', '0006_booking_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
