# Generated by Django 5.1.7 on 2025-04-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='total_deposit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='wallet',
            name='total_withdrawn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
