# Generated by Django 5.1.7 on 2025-05-01 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_total_deposit_wallet_total_withdrawn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
